### ISSUE TITLE
Eventi

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#1]
vista Secondo livello Calendario Eventi e primo livello il filtro x data è messo +1day, ma nel mio caso hanno proprio un evento x oggi ed era già scomparso dalla lista, lasciando solo now si vede

**Comment by arturu** [comment]
Ho fixato con `-1 day` perché l'intenzione è quella di far vedere l'evento nella lista degli eventi attivi anche il giorno dopo la data di fine. Questo perché alcuni utenti cercano l'evento appena finito nello stesso posto in cui l'hanno trovato prima dell'inizio, quindi lasciandolo nella stessa posizione lo trovano più facilmente.
