### ISSUE TITLE
Sottotitolo

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#11]
![immagine](https://github.com/ouitoulia/diagraphe/assets/12139795/bd13c037-a9ff-4133-9ada-a0207bf1924f)

https://dev.liceomorgagni.it/didattica/i-progetti-delle-classi

mi dicono che la frase "I progetti ideati dai docenti della scuola." è vincolante, dato che per esempio l'unico progetto presente è ideato dagli studenti

**Comment by arturu** [comment]
L'originale è "I progetti creati dai docenti della scuola e a disposizione di tutti.", potremmo scrivere: 

A) "I progetti sviluppati dalla comunità scolastica e accessibili a tutti."
B) "I progetti sviluppati dalla comunità scolastica e a disposizione di tutti."

Altre cose non mi vengono in mente. Al posto del verbo "creare" ho usato un altro, il verbo creare sembra più una traduzione impropria dall'inglese (`create`) che non italiano. 
Hai alternative migliori rispetto a "sviluppare"?

**Comment by akamizi** [comment]
Mi dicono soluzione A; come alternativa possibile a sviluppare (ma andrebbe bene) è "ideati"
