### ISSUE TITLE
Visualizzazione materie

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#12]
![immagine](https://github.com/ouitoulia/diagraphe/assets/12139795/1269ea7a-c6c8-4fd7-80d1-b1bfb02acb05)

https://dev.liceomorgagni.it/didattica/le-schede-didattiche/secondaria-di-secondo-grado/il-goal-8-dellagenda-2030-percorso-trasversale

quando ci sono più materie la visualizzazione non è ottimale

**Comment by arturu** [comment]
Potremmo separarle da virgola o da `-` per lasciare leggero il testo. Oppure usare il componente badge o chip, però appesantire il sottotitolo con il componente badge o chip non mi sembra una buona soluzione.

Mettiamo virgola?

**Comment by akamizi** [comment]
proviamo virgola

**Comment by arturu** [comment]
Al prossimo rilascio del tema ci sarà la virgola.
![Schermata del 2024-04-10 10-28-44](https://github.com/ouitoulia/diagraphe/assets/4628942/f6e4f2d4-5087-4ddb-8931-4def635fb013)
