### ISSUE TITLE
Numero di elementi visualizzati nella pagina Servizi

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#14]
Non è proprio una issue: dicono che sarebbe preferibile la scelta del template ufficiale
https://italia.github.io/design-scuole-pagine-statiche/scuole-sezione-servizi.html
di mettere tutti i servizi, non gli piace che alcuni servizi importanti non siano immediatamente visibili.
Come dicevo non è proprio una issue, ma è un problema che anche i comuni ponevano, ed anche lì la soluzione del template ufficiale era ottimale. In quel caso la soluzione era diversa perché nei comuni i servizi sono centinaia

**Comment by arturu** [comment]
Rispetto alle pagine statiche cambia solo:

1) gli "elementi per pagina" per le view "Personale scolastico" e "Famiglie e studenti" sono 3, ho fatto così per rendere la pagina più leggera e per non farla scrollare tanto al cambio pagina, a limite possiamo aumentare il numero di elementi per pagina e vedere come va (tenendo sempre d'occhio le performance);
2) l'header hero è usato per l'intestazione dei percorsi di studio, io direi di lasciarlo, separa meglio le due parti, comunque sì, in linea di massima si può cambiare lasciando solo l'`h2` come nelle pagine statiche.

La cosa che andrebbe sistemata è il font nella card. Nelle pagine statiche il font è sans-serif, allineato in verticale con il titolo e un corpo più piccolo; però bisogna considerare che in bootstrap-italia v2 le impostazioni del font presente nel body delle card è: serif con corpo più grande, visto che è un aggiornamento rispetto alla v1.6 penso che dovrebbe rimanere come è, va solo allineato.

Che ne pensi?

**Comment by akamizi** [comment]
sull'header hero non hanno obiettato nulla così come su font, è che secondo loro i servizi si dovrebbero vedere senza slideshow, provo a modificarlo sul mio, non è detto che debba essere così per tutti.
Lascerei font così, aggiornati

**Comment by akamizi** [comment]
nel mio caso può andare:
https://dev.liceomorgagni.it/servizi

**Comment by arturu** [comment]
Per non farti piallare la modifica all'aggiornamento, fai uno script sh che lancia l'aggiornamento e subito dopo importa la tua configurazione modificata. Se vuoi rimanere sul semplice magari la configurazioni da aggiornare mettile nel tuo sub-theme in `config/upèdate` e lo script ti esce più o meno così:

```sh
#!/usr/bin/env bash

bash <(curl -s -H "Cache-Control: no-cache" "https://raw.githubusercontent.com/ouitoulia/diagraphe/10.2.x/scripts/utility__upgrade_dev_env.sh")

# poi metti le tue cose qua
drush config:import --partial -y --source=/path/sub-theme/config/update
```
Se vuoi fare robe più complesse magari un custom module con delle conf personalizzate, vabbè vedi tu, sai come fare :) 

Direi che possiamo segnare come risolto?

**Comment by akamizi** [comment]
sì sì
