### ISSUE TITLE
errore

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#17]
Non ho fatto in tempo a verificare, ma la pagina del progetto demo mi va in errore sul sito di demo:

TypeError: Drupal\twig_tweak\TwigTweakExtension::drupalField(): Argument #3 ($id) must be of type string, null given, called in /var/opt/www/scuola/vendor/twig/twig/src/Environment.php(360) : eval()'d code on line 98 in Drupal\twig_tweak\TwigTweakExtension::drupalField() (line 200 of /var/opt/www/scuola/web/modules/contrib/twig_tweak/src/TwigTweakExtension.php).

**Comment by arturu** [comment]
Ti manca il campo "Tipologia del progetto" oppure è vuoto (versioni fa non esisteva, forse per questo motivo il nodo è salvato senza questo campo). Comunque se lanci lo script di aggiornamento compreso l'aggiornamento dei dati demo dovrebbe andare tutto ok.

![Schermata del 2024-04-14 15-02-52](https://github.com/ouitoulia/diagraphe/assets/4628942/3fcf7b73-42ad-4c47-817c-008fdd4effc0)

**Comment by akamizi** [comment]
Mi dimentico sempre di aggiornare i dati demo, era quello
