### ISSUE TITLE
Vista finanziamenti con parametro

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#18]
Siccome già so che vorranno loghi e link con l'elenco finanziamenti già filtroto per PON e PNRR pensavo che forse basterebbe aggiungere un parametro di filtro alla vista.
Che ne dici?

**Comment by arturu** [comment]
dopo gli ultimi aggiornamenti di #15 penso che si possa chiudere?

**Comment by akamizi** [comment]
ok
