### ISSUE TITLE
Capolettera

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#19]
Mi sembrava di aver fatto una issue su questo ma non la ritrovo.
I capolettera dovrebbero essere applicati solo al primo paragrafo, siccome mi sembra solo un problema di css, dovrebbe bastare un p:first o qualcosa del genere

**Comment by arturu** [comment]
Se non ricordo male forse me lo avevi scritto in un messaggio o mail, non ricordo di preciso
