### ISSUE TITLE
Lazy load

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#20]
Ho visto che aggiungendo l'attributo loading="lazy" sulla riga 102 del file 
web/themes/contrib/skenografia/templates/views/primo_livello/didattica/views-view--primo-livello-didattica--page-1.html.twig
l'app di valutazione guadagna 4 punti % nella valutazione di velocità

**Comment by akamizi** [comment]
ti mando anche la versione webp

**Comment by akamizi** [comment]
ho appena verificato che l'uso dell'immagine in formato webp ci fa guadagnare altri 8 punti %

**Comment by arturu** [comment]
fatto, chiudo
