### ISSUE TITLE
Versione del tema

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#21]
Per superare questo punto
https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html#criterio-c-sc-1-3-utilizzo-di-temi-per-cms-content-management-system
mi hanno detto che è possibile mettere il codice nel css anche se non è quello "ufficiale", per i comuni ho fatto così e la preasseverazione è passata.

https://www.comune.narni.tr.it/themes/contrib/scaenographia/version.css

**Comment by arturu** [comment]
Ottimo, allora sviluppo un'action nel repo del tema e lo faccio scrivere in automatico con la versione corrente.
