### ISSUE TITLE
Ricerca

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#22]
Per passare la valutazione dell'app bisogna modificare il pulsante di ricerca sia nella struttura html che nei data-element
![immagine](https://github.com/ouitoulia/diagraphe/assets/12139795/6d8e4373-e2fe-4f4f-bdf3-ced53e825924)

poi bisognerà personalizzare l'html della faccetta Argomenti perché abbia un data-element
https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html#raccomandazione-r-sc-1-1-vocabolari-controllati

https://dev.liceomorgagni.it/risultati-ricerca

**Comment by arturu** [comment]
Penso che questa ormai si possa chiudere
