### ISSUE TITLE
Contenuti correlati

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#26]
Ti giro direttamente la domanda che mi hanno fatto, non so se è possibile.

E’ possibile fare in modo che tra i contenuti correlati non compaia il documento stesso?

**Comment by akamizi** [comment]
si può fare, l'ho testato:

https://www.drupal.org/node/131547

**Comment by arturu** [comment]
Sì, è una di quelle cose che mi sono accorto mentre facevo altro, "Poi fixo tanto è facile"... Grazie :+1:
