### ISSUE TITLE
Link sbagliato nel blocco Didattica

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#27]
Nel template
web/themes/contrib/skenografia/templates/views/primo_livello/didattica/views-view--primo-livello-didattica--page-1.html.twig
è sbagliato il link del pulsante "Vai alla presentazione della scuola"
link corretto: /scuola/presentazione

**Comment by arturu** [comment]
https://github.com/ouitoulia/skenografia/commit/fdb2f9343ba182eb146dc0ae4af4884f6977e49d
