### ISSUE TITLE
Issue forse di BI

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#29]
Ho trovato nel debug questo:

 INVALID FILE NAME SUGGESTIONS:
   See https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme_suggestions_alter
   views_view_bi_carousel
   views_view_bi_carousel__slider_hp

vedo ora che c'è una patch proposta proprio a BI
https://www.drupal.org/project/bootstrap_italia/issues/3387106

**Comment by akamizi** [comment]
Vedo che però l'avevi fatta la modifica... non riesco a capire cosa non gli piaccia

**Comment by arturu** [comment]
Non ho avuto tempo per rispondere a https://www.drupal.org/project/bootstrap_italia/issues/3387106#comment-15335334 ma quel file era già stato fixato con altro metodo. Comunque nel caso del carousel va pachtato l'hook presente nel sottomodulo di bootstrap_italia
