### ISSUE TITLE
Aggiunta materie primaria e infanzia

### ISSUE THREAD

**Issue by icbrs** [ouitoulia/diagraphe#30]
Ciao a tutti! Ben ritrovati :))

Dato che nell'architettura non mi sembra ci siano indicazioni in tal senso, forse nel vocabolario Materie della tassonomia si potrebbero aggiungere i campi di esperienza della scuola dell'infanzia e le materie della scuola primaria.

Ci sarebbe anche da capire se aggiungere il Sostegno anche se non è esattamente una materia che contribuisce al monte ore.

 I campi di esperienza dell'infanzia sono:

Il sè e l'altro
Immagini, suoni e colori
Il corpo e il movimento
I discorsi e le parole
La conoscenza del mondo
Sostegno (c'è sempre questo)

Se non sbaglio per l'infanzia la classe di concorso è unica: AAAA – Infanzia – Posto comune

Nella primaria, per il Comprensivo nel quale lavoravo avevo messo questo elenco:

Arte e Immagine
Educazione fisica
Geografia
Inglese
Italiano
Matematica
Musica
Ora alternativa alla Religione
Religione
Scienze
Sostegno
Storia
Tecnologia 

Bisogna vedere se le materie si possono raggruppare per ambiti e le classi di concorso.
Anche primaria dovrebbe essere unica: EEEE – Primaria – Posto comune.

**Comment by arturu** [comment]
Aggiungo le materie della primaria come le definisce il Ministero in questa pagina https://www.miur.gov.it/scuola-primaria

**Comment by arturu** [comment]
Stessa cosa per infanzia https://www.miur.gov.it/web/guest/scuola-dell-infanzia

**Comment by arturu** [comment]
Ho aggiunto le materie, grazie per la segnalazione :)

**Comment by icbrs** [comment]
Grazie a te Arturo! ;)

**Comment by icbrs** [comment]
Ci sarebbe un altro problemino che deriva dalla difficile gestione di tre ordini nella stessa scuola.
Nella visualizzazione classe, in basso appare "**Consiglio di classe**" e "Coordinatore di classe" per tutti gli ordini. In realtà dovrebbe apparire solo per la secondaria, mentre per infanzia e primaria sarebbe più giusto far mostrare **Consiglio di interclasse** (primaria) e di **intersezione** (infanzia). Ovviamente la stessa voce viene riportata anche nelle classi all'interno dei percorsi di studio.

Sempre per quanto riguarda la classe, il campo **orario** nell'architettura è obbligatorio. Se deve esserlo, primaria e soprattutto infanzia devono adoperarsi per renderne disponibile uno anche in quelle scuole dove non è mai stato pubblicato. L'ideale sarebbe che il campo fosse opzionale.
