### ISSUE TITLE
(non proprio una issue) Allegati Circolare

### ISSUE THREAD

**Issue by akamizi** [ouitoulia/diagraphe#7]
Nel mio caso hanno chiesto di mettere anche un campo allegati per mettere la stessa circolare in pdf, solo che la visualizzazione non è in linea con gli allegati di altri CT

https://dev.liceomorgagni.it/novita/le-circolari/calendario-esami-il-conseguimento-delle-certificazioni-cambridge-pet-first-cae

**Comment by arturu** [comment]
Ancora non ho fatto il campo per gli allegati, cmq intanto inserisco il template, riusa il campo allegati usato per il ct Documento

**Comment by akamizi** [comment]
https://dev.liceomorgagni.it/novita/le-circolari/calendario-esami-il-conseguimento-delle-certificazioni-cambridge

denghiù

**Comment by arturu** [comment]
Il campo è aggiunto, chiudo
